name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v4

      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Installing dependencies
        run: npm install
        working-directory: ./Frontend

      - name: Running linters
        run: npm run lint
        working-directory: ./Frontend

      - name: Formatting code
        run: npm run prettier
        working-directory: ./Frontend