name: Node.js CI

on:
  pull_request:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v4

      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Installing dependencies in Frontend
        run: npm install
        working-directory: ./Frontend

      - name: Running linters in Frontend
        run: npm run lint
        working-directory: ./Frontend

      - name: Formatting code in Frontend
        run: npm run prettier || echo "Prettier check completed with warnings"
        working-directory: ./Frontend

      - name: Installing dependencies in Backend
        run: npm install
        working-directory: ./Backend

      - name: Initialising localstack container
        run: ./build_package.sh
        working-directory: ./Backend

      - name: Deploying resources on localstack
        run: ./deploy_lambda.sh
        working-directory: ./Backend

      - name: Running tests
        run: npm test
        working-directory: ./Backend

      - name: Running linters in Backend
        run: npm run lint
        working-directory: ./Backend

      - name: Formatting code in Backend
        run: npm run prettier || echo "Prettier check completed with warnings"
        working-directory: ./Backend